id: A748FE49B
base_file: fCB62.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:55:02.913244
  last_modified_at: 2022-05-30 20:55:02.913251
