id: A748FE49B
base_file: fCD5E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:55:02.916247
  last_modified_at: 2022-05-30 20:55:02.916252
